sudo: required

services:
  - docker

language: generic

env:
- DISTRI=ubuntu DESKTOP=xfce
- DISTRI=ubuntu DESKTOP=icewm
- DISTRI=centos DESKTOP=xfce
- DISTRI=centos DESKTOP=icewm

script:
  - docker build -t local/${DISTRI}-${DESKTOP}-vnc -f ./Dockerfile.${DISTRI}.${DESKTOP}.vnc .
after_success:
  - bash .build/trigger_dockerhub.sh ${DISTRI}-${DESKTOP}-vnc

## use standard notification to committer
#notifications:
#    recipients:
#      - "testautomatisierung@consol.de"
#    on_success: change # default: change
#    on_failure: always # default: always
